<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.minefit.xerxestireiron</groupId>
        <artifactId>FLupdate</artifactId>
        <version>2.6</version>
    </parent>

    <artifactId>FarLandsAgain</artifactId>
    <packaging>jar</packaging>

    <dependencies>
        <!-- Modules internes du projet -->
        <dependency>
            <groupId>com.minefit.xerxestireiron</groupId>
            <artifactId>Utility</artifactId>
            <version>2.6</version>
        </dependency>
        <dependency>
            <groupId>com.minefit.xerxestireiron</groupId>
            <artifactId>v1_21_R1</artifactId>
            <version>2.6</version>
        </dependency>

        <!-- Paper API -->
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>${paper.version}</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>FarLandsAgain-${project.version}</finalName>

        <!-- AJOUTER ICI -->
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <artifactSet>
                                <includes>
                                    <include>com.minefit.xerxestireiron:*</include>
                                </includes>
                            </artifactSet>
                            <filters>
                                <filter>
                                    <artifact>*:*</artifact>
                                    <excludes>
                                        <exclude>META-INF/*.SF</exclude>
                                        <exclude>META-INF/*.DSA</exclude>
                                        <exclude>META-INF/*.RSA</exclude>
                                    </excludes>
                                </filter>
                            </filters>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
