<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.minefit.xerxestireiron</groupId>
        <artifactId>FLupdate</artifactId>
        <version>2.6</version>
    </parent>

    <artifactId>v1_21_R1</artifactId>
    <packaging>jar</packaging>

    <dependencies>

        <!-- API pour compiler les classes publiques -->
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-api</artifactId>
            <version>1.21.4-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>

        <!-- Paper avec Mojang mappings (JAR local) -->
        <dependency>
            <groupId>io.papermc.paper</groupId>
            <artifactId>paper-server</artifactId>
            <version>1.21.4</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/paper-1.21.4.jar</systemPath>
        </dependency>

        <!-- Minecraft Server (JAR local) -->
        <dependency>
            <groupId>com.mojang</groupId>
            <artifactId>minecraft-server</artifactId>
            <version>1.21.4</version>
            <scope>system</scope>
            <systemPath>${project.basedir}/libs/minecraft_server.1.21.4.jar</systemPath>
        </dependency>

        <!-- Dépend du module Utility -->
        <dependency>
            <groupId>com.minefit.xerxestireiron</groupId>
            <artifactId>Utility</artifactId>
            <version>2.6</version>
        </dependency>
    </dependencies>

</project>
